### ISSUE TITLE
mdb_put: MDB_MAP_FULL: Environment mapsize limit reached

### ISSUE THREAD

**Issue by olexij-christian** [2nd/lmdb-cli#10]
When work with already maked db have this error

mdb_put: MDB_MAP_FULL: Environment mapsize limit reached

How to growth mapsize limit?

**Comment by karlseguin** [comment]
Not really sure why it was done this way, but you can pass something like `-growth 1.25` and it'll grow it by 25% based on the current file size.

**Comment by olexij-christian** [comment]
`-growth 1.5` works for me. Thank you very much!
This command works perfect:
`lmdb-cli -db db -c "set foo bar" -growth 1.5`
