### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by flintinatux** [2nd/lmdb-cli#3]
I'm interested in using this to initialize new LMDB files, but I'm not quite sure how to install it for use.  Do you have any instructions to install it as an executable file?

**Comment by karlseguin** [comment]
I got a linux version built through github actions. If that works for you, you can download it here:
https://github.com/2nd/lmdb-cli/releases/tag/0.0.1

I'll need more time to look into why it failed to build a windows and osx binary though.

On OSX, if you have a relatively recent version of Go installed, you can download the source (same link as above), untar, cd, and run: `go build -o lmdb-cli main.go`  to generate a `lmdb-cli` binary.

You _may_ need to install xcode stuff via `xcode-select install`.

I'll update this issue if I can get the osx/win binaries built through github actions.

**Comment by flintinatux** [comment]
Thanks for the response!  I was able to get it installed in the end with `go get github.com/2nd/lmdb-cli`.  (I never use `go`, so I found that on StackOverflow.)  Good to know that's there's also a prebuilt option.
