### ISSUE TITLE
Is it possible to create a new db with the MDB_NOSUBDIR flag?

### ISSUE THREAD

**Issue by flintinatux** [2nd/lmdb-cli#4]
I'd like to use this CLI tool to create an LMDB database for use with `dnsdist`, which [requires the `MDB_NOSUBDIR` flag to be set](https://dnsdist.org/reference/kvs.html#newLMDBKVStore).  The end result should be a single file, not a directory.

However, when I tried to create a new LMDB database earlier with `lmdb-cli`, it created a directory.  Is is possible to create it as a file instead?

**Comment by karlseguin** [comment]
If you grab the latest, you can pass `-dir=false` at the command line and it'll then use the `MDB_NOSUBDIR` flag.

**Comment by flintinatux** [comment]
Thank you so much!  That works perfectly.  And the tagged releases make it super-simple to install in Docker.  Thanks again!
