### ISSUE TITLE
Update readme.md, fix (or update) link for symas.com/lmdb

### ISSUE THREAD

**Issue by cointastical** [2nd/lmdb-cli#7]
My mistake ... after created Pull Request #6, I deleted the fork from my repo, and it closed the pull request.

So re-adding a mention of it, as an Issue here.

https://github.com/2nd/lmdb-cli/pull/6/commits/06fd91b7b4242e091c1069b3d857bbd3a1937a70

**Comment by karlseguin** [comment]
Thanks, fixed.
